#!/bin/bash

clear
echo "Salut! Zii numele tau (nume prenume, ex. Gardus Matei): "
read -r STUDENT_SURNAME STUDENT_NAME
echo "Scrie repede numele celor doua probleme EXACT separate cu spatiu:"
read -r ID_PROB1 ID_PROB2

ORIGINAL_DIR=$(pwd)

FOLDER_PROB1=$(find . -type d -name "$ID_PROB1 *")
FOLDER_PROB2=$(find . -type d -name "$ID_PROB2 *")
FOLDER_PROB1=${FOLDER_PROB1:2}
FOLDER_PROB2=${FOLDER_PROB2:2}

echo "Prima problema gasita: $FOLDER_PROB1"
echo "A doua problema gasita: $FOLDER_PROB2"

cd ~/Desktop
mkdir "$STUDENT_SURNAME $STUDENT_NAME"
cd "$HOME/Desktop/$STUDENT_SURNAME $STUDENT_NAME"
mkdir "${FOLDER_PROB1}"
mkdir "${FOLDER_PROB2}"

cp "$ORIGINAL_DIR/${FOLDER_PROB1}/main.cpp" "$HOME/Desktop/$STUDENT_SURNAME $STUDENT_NAME/${FOLDER_PROB1}/main.cpp"
cp "$ORIGINAL_DIR/${FOLDER_PROB2}/main.cpp" "$HOME/Desktop/$STUDENT_SURNAME $STUDENT_NAME/${FOLDER_PROB2}/main.cpp"

echo "Cleaning up..."
rm -r "$ORIGINAL_DIR/master.zip"

echo "Gata! Misto test, nu?"
sleep 2
clear
